[package]
name = "comandr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qt_core = "0.5.0"
qt_gui = "0.5.0"
qt_widgets = "0.5.0"
slint = "1.7.1"

[build-dependencies]
slint-build = "1.7.1"
